version: '3'
services:
  mongodb:
    image: mongo
    volumes:
     - ./data/db:/data/db
    container_name: mongodb
 online-shop:
   build:
     context: .
   container_name: online-shop
   depends_on:
     - mongodb
   ports:
     - 8100:8100
   env_file:
     - .env
