export default [
  {
    id: 1,
    name: '42mm Space Gray Aluminum Case with Black Woven Nylon',
    price: 249.99,
    discount: null,
    imageUrl: 'https://drive.google.com/uc?export=view&id=14C5tYz8H0dBgrRepcIMza-3iY0PDUTFZ',
    badge: null,
    validFrom: new Date('2020-01-01'),
    validUntil: new Date('2020-01-01'),
  },
  {
    id: 2,
    name: '42mm Space Gray Aluminum Case with Gold/Royal Blue Woven Nylon',
    price: 249.99,
    discount: null,
    imageUrl: 'https://drive.google.com/uc?export=view&id=1aWODK4OpseXZe1Glcikced_yn4PS-RaA',
    badge: null,
    validFrom: new Date('2020-01-01'),
    validUntil: new Date('2020-01-01'),
  },
  {
    id: 3,
    name: '42mm Space Gray Aluminum Case with Royal Blue Woven Nylon',
    price: 349.99,
    discount: null,
    imageUrl: 'https://drive.google.com/uc?export=view&id=1d8xNlNprcgRmDh7O4SEq2fcrIwiTvAHt',
    badge: null,
    validFrom: new Date('2020-01-01'),
    validUntil: new Date('2020-01-01'),
  },
  {
    id: 4,
    name: '42mm Space Gray Aluminum Case with Scuba Blue Woven Nylon',
    price: 399.99,
    discount: 25.00,
    imageUrl: 'https://drive.google.com/uc?export=view&id=1euBu7AuCuYlP4KU02cwjubsImMVGOqf_',
    badge: 'new',
    validFrom: new Date('2020-01-01'),
    validUntil: new Date('2020-01-01'),
  },
  {
    id: 5,
    name: 'Double Tour, 38mm Stainless Steel Case with Etain Leather Band',
    price: 199.99,
    discount: null,
    imageUrl: 'https://drive.google.com/uc?export=view&id=1Mr30uiOcsYS-fcvp6CtGA_uOmr43RTPo',
    badge: null,
    validFrom: new Date('2020-01-01'),
    validUntil: new Date('2020-01-01'),
  },
  {
    id: 6,
    name: 'Double Tour, 38mm Stainless Steel Case with Capucine Leather Band',
    price: 399.99,
    discount: 50.00,
    imageUrl: 'https://drive.google.com/uc?export=view&id=1aXroTnn-UTFk2DayuAPtKPyPVFiO8ihd',
    badge: 'sale',
    validFrom: new Date('2020-01-01'),
    validUntil: new Date('2020-01-01'),
  },
  {
    id: 7,
    name: 'Double Tour, 38mm Stainless Steel Case with Bleu Jean Leather Band',
    price: 349.99,
    discount: null,
    imageUrl: 'https://drive.google.com/uc?export=view&id=1Elr4Yqe4tJpU7G9SHEPFxTgpSMHyfj5C',
    badge: null,
    validFrom: new Date('2020-01-01'),
    validUntil: new Date('2020-01-01'),
  },
  {
    id: 8,
    name: 'Double Tour, 42mm Stainless Steel Case with Noir Leather Band',
    price: 249.99,
    discount: null,
    imageUrl: 'https://drive.google.com/uc?export=view&id=1pSEQevqKW7OB0D_WWC42uxvQUL932NtU',
    badge: null,
    validFrom: new Date('2020-01-01'),
    validUntil: new Date('2020-01-01'),
  }
]